# This is a comment
FROM erwinchang/ubuntu-12.04-32bit-build
MAINTAINER  erwin<m9207216@gmail.com>

# setting env
ENV CROSS_COMPILE arm-none-linux-gnueabi-
ENV TOOLS_ARM_2009q1_DIR /opt/arm-2009q1
ENV PATH ${PATH}:/opt/arm-2009q1/bin

# add file
ADD arm-2009q1-203-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.gz /opt
